add workflows + issue template
pop-os/cosmic-files pull request #128
Opened 2024-04-24 21:57 UTC by wiiznokes

2024-05-01 06:33 UTC, ryanabx commented
What is the prettier workflow for? I've only heard of rustfmt in regards to rust formatting

2024-05-01 12:08 UTC, wiiznokes commented
I format other files like `.md`. https://github.com/prettier/prettier

2026-07-23 20:05 UTC, jacobgkau requested changes
This could be closed since CI's been implemented now.

If you're still interested in proposing issue templates, see the comments I left, and reference the issue templates in our older repos that have them, e.g.: https://github.com/pop-os/popsicle/blob/master/.github/ISSUE_TEMPLATE.md

2026-07-23 20:05 UTC, jacobgkau commented on .github/workflows/ci.yml
> +name: Continuous Integration
We have a CI file now. This can probably be dropped, or at least needs to be rebased.

2026-07-23 20:05 UTC, jacobgkau commented on .github/workflows/prettier.yml
> +name: Prettier
Do we use this in any other repos? It seems redundant with rustfmt, at a glance.

2026-07-23 20:05 UTC, jacobgkau commented on .github/ISSUE_TEMPLATE/blank_issue.md
> +name: Blank Issue (do not use this for bug reports or feature requests)
If it shouldn't be used for bug reports or feature requests, then what's the use-case of putting it there?

2026-07-23 20:05 UTC, jacobgkau commented on .github/ISSUE_TEMPLATE/bug_report.md
> +#### Possible Solutions:
I don't think we need this category.

2026-07-23 20:05 UTC, jacobgkau commented on .github/ISSUE_TEMPLATE/bug_report.md
> +#### Possible Additional Information:
This can go at the end, just be called "Additional information:", and can also replace the "Logs, Panic Messages, Stack Traces:" category since that's all additional information.

2026-07-23 20:05 UTC, jacobgkau commented on .github/ISSUE_TEMPLATE/bug_report.md
> +#### Operating system
This and the next header are missing colons that the rest of the headers have. The capitalization structure should also be consistent across all of these titles.

2026-07-23 20:05 UTC, jacobgkau commented on .github/ISSUE_TEMPLATE/bug_report.md
> +#### Expected Result:
Let's use the word "behavior" instead of "result" to better match our other repos with issue templates.

2026-07-23 20:05 UTC, jacobgkau commented on .github/ISSUE_TEMPLATE/feature_request.md
> +#### Who Benefits From The Change(s)?:
Not sure this adds a lot of value beyond the previous "Use Case" category.

2026-07-23 20:05 UTC, jacobgkau commented on .github/ISSUE_TEMPLATE/feature_request.md
> +#### Proposed Change:
Maybe put this first and call it "Feature Description" or something like that.

2026-07-23 20:34 UTC, wiiznokes commented
Yeah we can close this. Thanks for the review tho

2026-07-23 20:34 UTC, closed without merging