Update cosmic_files.ftl Pl translation
pop-os/cosmic-files pull request #303
Opened 2024-07-27 09:28 UTC by VandaLHJ

Added operations and dialog

2024-07-29 10:45 UTC, Kartonrealista commented on i18n/pl/cosmic_files.ftl
> +original-file = Oryginaly plik
"Oryginal**n**y", not "Oryginaly"

2024-07-29 10:45 UTC, Kartonrealista requested changes
Please fix this typo

2024-07-29 11:27 UTC, VandaLHJ commented
Fixed typo

2024-07-31 13:54 UTC, jackpot51 approved these changes

2024-07-31 13:54 UTC, merged